name: BookSearcher
options:
  bundleIdPrefix: host.agily
  xcodeVersion: '12.0'
targets:
  BookSearcher:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources:
      - BookSearcher
